### ISSUE TITLE
latest version of o2g.hiposfer.com returns invalid zip file

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#105]
following the links in the README (https://github.com/hiposfer/osmtogtfs#web-api-with-overpass-query) returns an invalid zip file (cannot be opened).

The zip file is also extremely small (`44 KB` for freiburg) which might indicate that this is a bug when building the file

**Comment by mehdisadeghi** [comment]
I noticed this today and have already a PR for it. However the zip file is valid but your client doesn't support it. You can open it with 7zip. I was going to switch the compression to DEFLATE which is almost universally supported, however need a bit more space, 160kb in this case.

What do you think?

**Comment by carocad** [comment]
I think going with the safe option is better in this case. Sure we were a bit of storage here but the size of the file is so small that it barely matters; compared to the previous 12mb vs 2mb. 160kb is great :)
