### ISSUE TITLE
Process master routes

### ISSUE THREAD

**Issue by mehdisadeghi** [hiposfer/osmtogtfs#17]

**Comment by carocad** [comment]
@mehdisadeghi what do you mean by this? what information can you extract from this that is not available somewhere else?

**Comment by mehdisadeghi** [comment]
@carocad quote from [route_master](http://wiki.openstreetmap.org/wiki/Relation:route_master) page on OSM website:

    Relations of type route_master contain all the direction and variant routes and the information that belongs to the whole service.

By processing them I want to make sure that we are not missing any route related information. I'm not yet sure whether we can add anything to the current GTFS output however.

**Comment by mehdisadeghi** [comment]
Closing as seems so far unnecessary. Feel free to reopen if needed.
