### ISSUE TITLE
create an "unknown agency" placeholder

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#2]
follow up on #1 

I just thought of this, but would it be possible to have an "unknown agency" placeholder?

I saw that in the routes there are lots of agencies missing which got me thinking about it. Technically it should not be the job of the routing engine to deal with missing data (otherwise having a separate script makes little sense, I think), therefore I think that the best alternative (only regarding agencies) would be to have an agency (id = -1, name= unknown)? Which lets us avoid missing the value at runtime.

**Comment by mehdisadeghi** [comment]
>  Technically it should not be the job of the routing engine to deal with missing data

I strongly agree. We have to keep concerns separated.

> I saw that in the routes there are lots of agencies missing

I'm not yet sure whether the data for those agencies are really missing. Perhaps the `route_master` relations contain some data on agencies, or some other tags.
