### ISSUE TITLE
Don't process ways

### ISSUE THREAD

**Issue by mehdisadeghi** [hiposfer/osmtogtfs#22]
At the moment we process ways in order to _guess_ time zone for some agencies. If we drop processing ways, we would process the same OSM files up to 40% faster (At least I was able to process Hessen file on my laptop). For some agencies we wouldn't know the timezone however, but they are not much.

What do you think @carocad?

**Comment by carocad** [comment]
is it actually possible to fully drop ways? I mean you still need those for figuring out the parts of a route/trip/shape right? I havent fully checked the code for that but I think I was doing something similar in `kamal`.

I thought that you were getting the timezone from the relation tag. Is that so? if it is then you could just loop over the nodes of a relation until you figure out the timezone just by using those.

> For some agencies we wouldn't know the timezone however, but they are not much.

**Comment by mehdisadeghi** [comment]
> I mean you still need those for figuring out the parts of a route/trip/shape right?

Except for guessing timezone, I have not used ways. Of course they are part of many relations, but the scope of GTFS is limited, so I didn't need extra information for constructing the feed (of course except the scheduling info which is partially available).

> I thought that you were getting the timezone from the relation tag.

Not directly, from its members, i.e. nodes and ways. Relations do not have locations, that info is available via their members.

> it is then you could just loop over the nodes of a relation until you figure out the timezone just by using those.

This is precisely what I've done. However, some relations have ways too. To process those I have to process all the ways beforehand which increases the processing time and required memory. Since a limited number of relations are purely constructed from anything except node, I thought it could be a good trade-off to make the script faster.

**Comment by carocad** [comment]
@mehdisadeghi I think in the long run we might need to process ways since (as always) things tend to complicate in the real world. AFAIK it is possible to specify things like platform start/end and in GTFS files. I think other way-related fields can also be added to GTFS.

however I think that for the time being it is preferable to keep things simple. If it improves the running time and you can substitute its need with something else then I dont see any problem with it.

👍

**Comment by mehdisadeghi** [comment]
@carocad I agree with you. I'll keep the ways in place, we have to take other measures in order to increase performance, CPU and memory-wise.
