### ISSUE TITLE
consider guessing the agency language and timezone  from osm data

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#3]
follow up on #1 

NOTE: I am not so sure anymore if it makes sense to have this. I am creating the ticket however to have an open discussion about it. The reason is that an agency could be in another country, yet use the infrastructure for its purposes, which sort of beats the purpose :(

you could probably infer the "agency_timezone, agency_lang" based on the lat, lon coordinates that you are processing

**Comment by mehdisadeghi** [comment]
> you could probably infer the "agency_timezone, agency_lang" based on the lat, lon coordinates that you are processing

Each relation is tagged with `operator` and there are many nodes related to it. Most probably they would be in the same time zone but it is not guaranteed.

**Comment by mehdisadeghi** [comment]
If a route is stretched within multiple time-zones there is no way to accurately guess the agency's timezone. However, I will ignore this, since our naive approach will cover most of the existing routes.

**Comment by mehdisadeghi** [comment]
I would leave out `language_code` for the time being. It is an optional entry in GTFS feed and very tricky to guess, actually we have no idea what the language of the agency is. What do you think @carocad?
