### ISSUE TITLE
Populate agency URLs

### ISSUE THREAD

**Issue by mehdisadeghi** [hiposfer/osmtogtfs#30]
We have to figure out a way to augment agency.txt with agency URLs.

**Comment by carocad** [comment]
@mehdisadeghi I remember that before you had an agency url there. I dont remember if it was an OSM thing or how you did it though.

I just checked OSM and they do have some information on agencies but it is very general and it doesnt point to the actual agency URL but to the OSM `wiki`.

See here:
- traffiQ - https://wiki.openstreetmap.org/wiki/Rhein-Main-Verkehrsverbund
- OSM - https://www.openstreetmap.org/relation/167520
