### ISSUE TITLE
investigate saarland empty routes

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#31]
I just tried osmtogtfs on Saarland and found out that several files are empty :(

Do you know what might be the cause?

[saarland.zip](https://github.com/hiposfer/osmtogtfs/files/1710840/saarland.zip)

**Comment by carocad** [comment]
my mistake !!

I totally forgot that you put the option to integrate dummy data or not. However that made me realize something: Would it be possible to print the config of `osmtogtfs` before it is executed?

Since the terminal description only says [OPTIONS] it is not possible to know which values were applied as default which can definitely be useful for a beginner :)

**Comment by mehdisadeghi** [comment]
> my mistake !!

No problem!

> Would it be possible to print the config of osmtogtfs before it is executed?

Yes of course! I think I had put the default values in the docs of each option. I'll have a second look.

**Comment by mehdisadeghi** [comment]
> Would it be possible to print the config of osmtogtfs before it is executed?

If you use `osmtogtfs --help`, it will show the default values that will be used (inside the docs).

To make it more explicit, I added some more logging to the output. You have to append `--loglevel DEBUG` to see them.
