### ISSUE TITLE
remove trips with a single stop

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#32]
@mehdisadeghi I thought that we already had this one solved but I am seeing something weird in the files so I am openning an issue :)

Some stop_files.txt entries have a single stop for a trip. [Here](https://github.com/hiposfer/osmtogtfs/blob/master/tests/out/stop_times.txt#L282) is an example. That line and the next one have a stop sequence of 0 which should be impossible since they should all be increasing :(

**Comment by mehdisadeghi** [comment]
Good catch @carocad! I also thought that it is resolved, but apparently it needs more work.

**Comment by mehdisadeghi** [comment]
@carocad while fixing this one, I realized there was another bug extracting stops. I fixed that too. Please see the updated output.
