### ISSUE TITLE
release a new version for fixed bugs

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#35]
I think it would be very useful ;)

**Comment by carocad** [comment]
my mistake !!
I didnt see that pip already had a new version

**Comment by mehdisadeghi** [comment]
Sorry about that! I was in doubt whether for a version bump I should create a PR and etc, or should we push versions directly? What do you think?

**Comment by carocad** [comment]
I would just push the version directly on the PR that creates the changes/fixes. No need for extra burocracy ;)

**Comment by mehdisadeghi** [comment]
v1.0.7 released.
