### ISSUE TITLE
investigate incosistent stop_sequence on Saarland

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#36]
While checking the output of osmtogtfs on the Saarland file (latest) I found out that lots of stop_sequences are created as 0,1.

I dont mean that the route has only 2 stops, but rather that somehow the dummy generator only created 2 stops for those even if the route has more.

Example:
- stop_times
```
trip_id,arrival_time,departure_time,stop_id,stop_sequence
75253851,05:00:00,05:00:30,263906742,0
75253851,05:20:00,05:20:30,5069917764,1
75253852,05:20:00,05:20:30,263906742,0
75253852,05:40:00,05:40:30,5069917764,1
75253853,05:40:00,05:40:30,263906742,0
75253853,06:00:00,06:00:30,5069917764,1
75253854,06:00:00,06:00:30,263906742,0
75253854,06:20:00,06:20:30,5069917764,1
75253855,06:20:00,06:20:30,263906742,0
75253855,06:40:00,06:40:30,5069917764,1
75253856,06:40:00,06:40:30,263906742,0
75253856,07:00:00,07:00:30,5069917764,1
75253857,07:00:00,07:00:30,263906742,0
75253857,07:20:00,07:20:30,5069917764,1
75253858,07:20:00,07:20:30,263906742,0
75253858,07:40:00,07:40:30,5069917764,1
75253859,07:40:00,07:40:30,263906742,0
75253859,08:00:00,08:00:30,5069917764,1
```

- [relation on Open Street Maps](https://www.openstreetmap.org/relation/7525385)

The relation on OSM clearly shows more than 1 stop, however for some reason the transformation is failing :(

**Comment by mehdisadeghi** [comment]
Done in #39

**Comment by mehdisadeghi** [comment]
@carocad Perhaps I should have asked you before closing! I assumed it was the same problem as having 12 stop_times and shapes repeated many times. Please feel free to reopen if it is not.
