### ISSUE TITLE
fix validation of dummy gtfs generation

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#37]
With the latest fixes a new set of bugs appeared on the feed validation :(

Here is the output from the Saarland export
[FeedValidator: tmp.zip](https://github.com/hiposfer/osmtogtfs/files/1731466/FeedValidator.tmp.zip)

**Comment by mehdisadeghi** [comment]
The validation should be part of tests. I'll update soon.

**Comment by mehdisadeghi** [comment]
@carocad 
Please see [fix-validation](https://github.com/hiposfer/osmtogtfs/tree/bug/fix-validation) branch. Still in progress but it addresses all the errors and only there remains the warnings.

**Comment by mehdisadeghi** [comment]
BTW, the file you've uploaded is broken.

**Comment by carocad** [comment]
> BTW, the file you've uploaded is broken.

Thanks for the info. I will download the saarland file again and update it 😉

**Comment by carocad** [comment]
@mehdisadeghi I remembered that we had discussed about the 24hours things in the trips as well as other validation issues and after checking I found out that in fact you already took care of it on this branch: https://github.com/hiposfer/osmtogtfs/commit/710a08f89ebf87b3b4cf0015a2fa45ce7f09916e

It turns out that those changes were never merged which would explain why we are facing the same issues :(

**Comment by mehdisadeghi** [comment]
>  I found out that in fact you already took care of it on this branch: 710a08f

@carocad I have completely repeated myself :/

**Comment by mehdisadeghi** [comment]
Honestly I don't remember why I have merged the changes to the `badge` branch instead of master. Sorry about that.

**Comment by mehdisadeghi** [comment]
I'm deleting the `badge` branch after inspecting its commits. I copied some of them into a new commit and the rest is simply out of date.

**Comment by mehdisadeghi** [comment]
Done in #39
