### ISSUE TITLE
consider having a heroky dyno for transforming osm url into a gtfs zip file

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#41]
This would allow us to have a fast prototyping and deployment without caring about new dependencies and old installations.

It is also easier to test since passing a URL is a no-brainer

I imagine it like `my-project.heroky.com/?osm=fdsafjdslkfmdsfdsof` where is the UriEncoded string of the actual URL.

The Python script would just fetch the osm file, run the transformation and return it as a zip file.

**Comment by mehdisadeghi** [comment]
That sounds good to me.

**Comment by mehdisadeghi** [comment]
@carocad I'm just looking at it, and apparently heroku does not support installing extra dependencies, in this case osmium. I think the only way would be deploying a docker image but I have never tried that.

**Comment by mehdisadeghi** [comment]
@carocad give the latest web ui a try before I turn this temporary server off!

[http://195.201.43.108:3000/](http://195.201.43.108:3000/)

**Comment by carocad** [comment]
I get an error when trying it with Tübingen Files. The `osh` extension is not recognized and if I try the `pbf` one then I get an stacktrace :(

**Comment by mehdisadeghi** [comment]
I'll give it a try to see what's the problem

**Comment by mehdisadeghi** [comment]
@carocad I just tried it with [Tübingen pbf file](http://download.geofabrik.de/europe/germany/thueringen-latest.osm.pbf) and it worked just fine with or without dummy flag set. I have no idea at the moment what could have gone wrong.

**Comment by carocad** [comment]
hey @mehdisadeghi sure thing. Here is the link to the Tuebingen files: https://download.geofabrik.de/europe/germany/baden-wuerttemberg/tuebingen-regbez.html

Here is a screenshot of the error that I get if I try with the `osm.bz2` file
<img width="917" alt="screen shot 2018-03-12 at 11 04 42" src="https://user-images.githubusercontent.com/10408729/37277601-7b6a6718-25e5-11e8-97b3-a25a9fe63a01.png">

This is a screenshot of the error that I get if I try with the `osh.pbf` file
<img width="1142" alt="screen shot 2018-03-12 at 11 07 03" src="https://user-images.githubusercontent.com/10408729/37277636-97e12bc0-25e5-11e8-9843-bea4c2adc945.png">

Hope it helps

**Comment by mehdisadeghi** [comment]
@carocad now it will accept any file and pass it to osmium. With osh you will still get some errors which I have fixed but are not available on this instance yet.

**Comment by mehdisadeghi** [comment]
@carocad `osmtogtfs` on Heroku: https://immense-plateau-92961.herokuapp.com/

**Comment by carocad** [comment]
@mehdisadeghi oh it is already fit for Heroku :) nice !!

Unfortunately I still get an error if I try to convert a file. This error is different though

<img width="735" alt="screen shot 2018-03-13 at 08 39 52" src="https://user-images.githubusercontent.com/10408729/37328465-939635d2-269a-11e8-894c-89245eaad329.png">

**Comment by mehdisadeghi** [comment]
Most probably MemoryError, try with a smaller file. Heroku hides the logs by default.

**Comment by mehdisadeghi** [comment]
@carocad see #60 and #61. See [http://o2g.herokuapp.com](http://o2g.herokuapp.com) for master branch. Each PR will a preview app of its own.
