### ISSUE TITLE
Switch to saarland osm file

### ISSUE THREAD

**Issue by mehdisadeghi** [hiposfer/osmtogtfs#42]
@carocad I am using Bremen's data because it is the smallest among all. Shall I switch to Saarland to make things simpler?

Bremen's pbf file is 16.9 MB while Saarland's is 34.8 MB

**Comment by carocad** [comment]
@mehdisadeghi it would make things easier for me for sure. But this is not a show stopper so just do as you think is best.

Also if we get #41 done then this loses relevance as our development cycle would be faster and less manual-work oriented.

**Comment by mehdisadeghi** [comment]
Saarland data is also included, plus its output. #45
