### ISSUE TITLE
consider checking the 'platform' tag to identify route stops

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#44]
From what I can see in the generated GTFS file, you are currently only taking the `public_transport 'stop'` as tag to identify route stops positions.

I think (though I am not sure) that OSM also uses the 'platform' tag to identify those. It might be worth to check those out and see if it is the case.

Example: https://www.openstreetmap.org/relation/7886858#map=11/49.2521/7.1706

**Comment by mehdisadeghi** [comment]
@carocad you are right. However, I think at least for creating shape.txt file I'll take all the nodes of a relation into account, regardless of their membership type (stop, platform, etc), because the difference is not much and it creates a more accurate shape for the route.

**Comment by carocad** [comment]
Sounds good to me
