### ISSUE TITLE
consider making the shape creation part of the standard output not of dummy

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#47]
AFAIK currently we are making the shapes have the same ID as the trips. Furthermore we only create those if the dummy flag is set.

However since the trips that we are creating are basically the OSM route relations, we can separate the trips from the shapes such that a single shape is created per `route` not per trip.

The main goal here is to reduce the size of the shape files and therefore the memory needed on the clients to hold that information

**Comment by mehdisadeghi** [comment]
> AFAIK currently we are making the shapes have the same ID as the trips.

Shape ids are irrelevant.

> Furthermore we only create those if the dummy flag is set.

As I understood from reading GTFS specs, a shape is the real path that a vehicle takes. So it is strongly bound to the trip (which we are generating with dummy flag).

I think we can decrease the number of generated dummy trips which will significantly decrease the size of shapes file.

**Comment by carocad** [comment]
> I think we can decrease the number of generated dummy trips which will significantly decrease the size of shapes file.

Yes we should also look into that

> As I understood from reading GTFS specs, a shape is the real path that a vehicle takes. So it is strongly bound to the trip (which we are generating with dummy flag).

Yes it is bound to the trip. My point was rather that you know in advance the limited set of shapes that a dummy trip might use i.e. since the trips are fake and generated based on the osm routes there is no other option than using one of those shapes. If a user selects the dummy flag it would only be a matter of linking the trip with the correct shape, but the shape had to exists before hand right? or are you generating the shape based on fake values as well?

**Comment by mehdisadeghi** [comment]
> If a user selects the dummy flag it would only be a matter of linking the trip with the correct shape

Find the _correct shape_ is tricky . Let's revisit [the definition for shapes.txt](https://developers.google.com/transit/gtfs/reference/#shapestxt):

> Shapes describe the physical path that a vehicle takes, and are defined in the file shapes.txt. Shapes belong to Trips, and consist of a sequence of points. Tracing the points in order provides the path of the vehicle. The points do not need to match stop locations.

Perhaps we can come up with a shape definition beforehand, which I'll mention soon. First your questions:

> the shape had to exists before hand right? or are you generating the shape based on fake values as well?

At the moment I take the fake route and the stops from the route that it belongs to and generate a fake shape for it.

Now that I think about it after a while, I think we can come up with a more useful shape.txt file. We can assume we have one shape per route, which is the route itself. Then we assign the same shape to every trip on that route.

What do you think?

**Comment by carocad** [comment]
> We can assume we have one shape per route, which is the route itself. Then we assign the same shape to every trip on that route.

@mehdisadeghi that sounds pretty good :)

**Comment by mehdisadeghi** [comment]
@carocad yeah, I just re-read what you had written in the opening of this post and realized I have repeated what you had suggested earlier! :D

**Comment by mehdisadeghi** [comment]
Done in #53
