### ISSUE TITLE
invert integer and decimal part of trip id

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#56]
hey @mehdisadeghi I ran into a very interesting issue today.

currently we are interpreting the trip id as a `double` and we fake the decimal part based on the calendar and a counter. However since those fake parts are after the decimal point the trip id `7525385.01` and the trip id `7525385.010` are read as the same number i.e. the last zero is ignored because it doesnt add any precision to a double :)

This is of course a bug from our design. I think that a quick fix would be to just invert the two double parts and to append the calendar entry (not prepend it). 

For example:
- trip id `7525385.01` becomes `10.7525385`
- trip id `7525385.010`  becomes `100.7525385`

I think that this can fix the problem, however I havent made a through check of it

Example trips.txt entries for saarland
```
route_id,service_id,trip_id,trip_headsign,shape_id
7525385,WE,7525385.01,"[Dummy]Luxembourg, Gare Centrale-to-Orscholz, Rehaklinik",7525385.017525385
7525385,WE,7525385.02,"[Dummy]Luxembourg, Gare Centrale-to-Orscholz, Rehaklinik",7525385.027525385
7525385,WE,7525385.03,"[Dummy]Luxembourg, Gare Centrale-to-Orscholz, Rehaklinik",7525385.037525385
7525385,WE,7525385.04,"[Dummy]Luxembourg, Gare Centrale-to-Orscholz, Rehaklinik",7525385.047525385
7525385,WE,7525385.05,"[Dummy]Luxembourg, Gare Centrale-to-Orscholz, Rehaklinik",7525385.057525385
7525385,WE,7525385.06,"[Dummy]Luxembourg, Gare Centrale-to-Orscholz, Rehaklinik",7525385.067525385
7525385,WE,7525385.07,"[Dummy]Luxembourg, Gare Centrale-to-Orscholz, Rehaklinik",7525385.077525385
7525385,WE,7525385.08,"[Dummy]Luxembourg, Gare Centrale-to-Orscholz, Rehaklinik",7525385.087525385
7525385,WE,7525385.09,"[Dummy]Luxembourg, Gare Centrale-to-Orscholz, Rehaklinik",7525385.097525385
7525385,WE,7525385.010,"[Dummy]Luxembourg, Gare Centrale-to-Orscholz, Rehaklinik",7525385.0107525385
7525385,WE,7525385.011,"[Dummy]Luxembourg, Gare Centrale-to-Orscholz, Rehaklinik",7525385.0117525385
7525385,WE,7525385.012,"[Dummy]Luxembourg, Gare Centrale-to-Orscholz, Rehaklinik",7525385.0127525385
7525
```

**Comment by mehdisadeghi** [comment]
Oh an interesting issue! And your solution sounds as interesting to me! :ok_hand:

**Comment by mehdisadeghi** [comment]
@carocad please see the PR #62 (there is also a review app for it!)
