### ISSUE TITLE
add OBDL license to output

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#57]
Since we are using OSM data to create the GTFS files we have to respect the license that that data comes with

**Comment by mehdisadeghi** [comment]
@carocad should we put a file [like this](https://github.com/enyst/licenses-db/blob/master/ODbL-1.0.txt) inside the generated feeds?

**Comment by carocad** [comment]
@mehdisadeghi that looks good :)

I think simply copy/pasting the file on the output zip/folder would be enough
