### ISSUE TITLE
missing route short name

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#69]
In `kamal` I decided to turn full validation on in the `dev` branch and throw an exception if the gtfs feed doesnt have the fields marked as `required` by the gtfs spec.

the route `short name` is one of those and unfortunately o2g doesnt seem to provide a default value for cases where OSM doesnt provide one.

I guess that using the route long-name would be enough for the time being? 🤔 

To pinpoint the error, it is convenient to just copy the content of the `saarland/routes.csv` file into this [website](http://www.convertcsv.com/csv-to-html.htm) which will convert it to a table that can be easily look through :)

EDIT: I thought that we have google python validation test integrated into this repo? shouldnt that fail in this case?

**Comment by mehdisadeghi** [comment]
From [GTFS spec](https://developers.google.com/transit/gtfs/reference/#routestxt):

> At least one of route_short_name or route_long_name must be specified, or potentially both if appropriate. If the route does not have a short name, please specify a route_long_name and use an empty string as the value for this field.

So a route could have no short name and still be valid if it has a long route name. That's why Google validation passes.

**Comment by carocad** [comment]
@mehdisadeghi I see, good to know that.

It means that my gtfs parsing logic is wrong :)
