### ISSUE TITLE
calculate time between stops based on distance not fixed

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#74]
Currently the time taken by a vehicle to travel from one stop to the next is fixed to `20 minutes`.

Obviously if the stops are very far apart, this is not a problem. However for nearby stops like with the `tram` or `bus`, this value doesnt make any sense.

This problem poped up because with kamal it is currently impossible to get a routing result that has any public transport in it. The reason for this is that since the time between each pair of stops is 20 minutes, it is always faster to walk than to take the public transport 😸

**Comment by mehdisadeghi** [comment]
`kamal` suggests the healthiest route then :laughing:
