### ISSUE TITLE
document id mapping

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#8]
Most data fetching done in this script is pretty straightforward i.e. name, location, lang, etc

However the id of agencies, routes, shapes, etc should be consistent between executions and well understood. Therefore it would be nice to have some documentation (wiki/readme?) about where does the id of each element come from (osm, hash, random number, etc)

**Comment by mehdisadeghi** [comment]
Except for agencies the rest come from OSM. I'll document this.
