### ISSUE TITLE
agency url not being filled

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#83]
follow up on https://github.com/hiposfer/osmtogtfs/pull/82

I have tried getting a gtfs feed with agency urls for several input files and they dont seem to work

This are the things that I have tried:
- Frankfurt region from overpass turbo query result
- Offenburg region from overpass turbo query result
- tuebingen region from geofabrik: http://download.geofabrik.de/europe/germany/baden-wuerttemberg/tuebingen-regbez.html

So far none of them give back the agency url, regardless of whether I use dummy or not :(

**Comment by mehdisadeghi** [comment]
I guess the query does not return url related tags that we have used to fetch agency urls.

**Comment by carocad** [comment]
@mehdisadeghi I thought that as well, however that would not explain why the tuebingen file didnt produce any results either :/

**Comment by mehdisadeghi** [comment]
@carocad 

> however that would not explain why the tuebingen file didnt produce any results either

It could be simply that there are no agency websites in the file. Currently we only check two extra tags for this: `contact:website` and `url`.

**Comment by mehdisadeghi** [comment]
@carocad as discussed over Slack I close this. Please feel free to reopen in case you see any agency url information on a OSM relation which is not reflected in `agency.txt` file.
