### ISSUE TITLE
consider using the frequencies.txt instead of a big stop_times files

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#84]
according to the GTFS spec it is possible to have a frequencies.txt file which together with the stop_times.txt describes the times at which a trip reaches the stops

> When trips are defined in frequencies.txt, the trip planner ignores the absolute values of the arrival_time and departure_time fields for those trips in stop_times.txt. Instead, the stop_times table defines the sequence of stops and the time difference between each stop.

Advantages:
- reduce the total amount of of entries that we have in the dummy output
- easier for humans to parse/understand since we dont have to scroll over thousands of lines
- no need for fancy algorithms to find patterns in the stop_times since it is given by default

Disadvantages:
- `kamal` would have to understand both formats and expand the frequencies at runtime to find the proper trip

Questions:
- should we make the frequencies.txt *required* for `kamal`? it would probably speed up the routing since we dont need to loop over thousands of `stop_times` entries

Reference:
- https://developers.google.com/transit/gtfs/reference/#frequenciestxt

**Comment by carocad** [comment]
current info on kamal data distribution: https://github.com/hiposfer/kamal/issues/180

**Comment by mehdisadeghi** [comment]
@carocad I know it took me a while to get to this but I'm eventually there :)

This feature falls in the domain of dummy patching a feed and using o2g to basically generate valid GTFS feeds for testing. This is a good thing, however kamal shouldn't rely on something totally random.

**Comment by carocad** [comment]
>  This is a good thing, however kamal shouldn't rely on something totally random.

Agree. Making it mandatory is definitely not a good solution. However right now I am developing `hive` to show the gtfs entities to the users so that they can edit those directly. 

The current way of handling stop_times makes it very problematic for a user to edit since it requires editing each entry manually. Since there might be hundreds of those just for a single route, it would be impossible for a user to contribute anything meaningful.

The alternative would be if we use frequencies.txt and let the user edit/add/remove those. Since the frequency immediately affect all trips of that route, it would be much more scalable.

That is actually what I meant by "making it required" .... since from the user perspective it becomes unbearable otherwise :/
