### ISSUE TITLE
consider storing example result in repo

### ISSUE THREAD

**Issue by carocad** [hiposfer/osmtogtfs#9]
The idea behind this is: result comparison

Every time that the script changes, it should be clear how does this affect the output files. Loading the code into ones head is rather problematic and error prone. 

A simple git diff and git log should be enough for evaluating the impact of the changes in the script even without understanding it.

I guess you could use the same saarland file that we have in `kamal` but that is not necessary at all

**Comment by mehdisadeghi** [comment]
Very good idea. I though using smallest possible OSM files for tests (and saving time) and I tried Maldive's one, but it lacks so many information that I dropped it. I have to add this to testing (and add some tests).
